//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiwiCrawler.Web.Extractdata_k {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblkId;
		protected global::System.Web.UI.WebControls.TextBox txtkUrl;
		protected global::System.Web.UI.WebControls.TextBox txtkPublishDateTime;
		protected global::System.Web.UI.WebControls.TextBox txtkContent;
		protected global::System.Web.UI.WebControls.TextBox txtkAddress;
		protected global::System.Web.UI.WebControls.TextBox txtkType;
		protected global::System.Web.UI.WebControls.TextBox txtkCaptureDateTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
