//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiwiCrawler.Web.Extractdata_k {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblkId;
	protected global::System.Web.UI.WebControls.Label lblkUrl;
	protected global::System.Web.UI.WebControls.Label lblkPublishDateTime;
	protected global::System.Web.UI.WebControls.Label lblkContent;
	protected global::System.Web.UI.WebControls.Label lblkAddress;
	protected global::System.Web.UI.WebControls.Label lblkType;
	protected global::System.Web.UI.WebControls.Label lblkCaptureDateTime;


       
    }
}
